spring:
  application:
    name: item-service
  rabbitmq:
    host: 192.168.64.141
    port: 5672
    username: admin
    passwors: admin
    
server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      